import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { LiffProvider } from "@/components/custom/LiffProvider";
import { cn } from "@/lib/utils";
import AppBar from "@/components/custom/app-bar";
import { Toaster } from "sonner";
import { Breadcrumb } from "@/components/custom/breadcrumb";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <LiffProvider liffId={process.env.NEXT_PUBLIC_LIFF_ID!}>
          <AppBar />
          <div className="px-2 pt-2">
            <Breadcrumb />
          </div>

          {children}
          <Toaster />
        </LiffProvider>
      </body>
    </html>
  );
}
